CREATE TABLE "CLIMATE_RAIN"."PROV_CLI_RHRE_DAY_SURF" 
   (	"CREGION" VARCHAR2(30) NOT NULL ENABLE, 
	"DDATE" DATE NOT NULL ENABLE, 
	"R_MAX" NUMBER(10,1), 
	"RMAX_STA" VARCHAR2(5), 
	"RS_STANUM" NUMBER(5,0), 
	"RS_STACODES" VARCHAR2(4000), 
	"RS_TTL" NUMBER(10,1), 
	"RS_M" NUMBER(10,0), 
	"RS_I" NUMBER(10,1), 
	"RS_A" NUMBER(10,2), 
	"RS_Z" NUMBER(10,1), 
	"D_IYMDHM" DATE, 
	 CONSTRAINT "PK_PROV_CLI_RHRE_DAY_SURF" PRIMARY KEY ("CREGION", "DDATE")
  USING INDEX  ENABLE
   ) ;
