CREATE TABLE "CLIMATE_RAIN"."PROV_CLI_RHRE_PROCESS_SURFAWST" 
   (	"CREGION" VARCHAR2(30) NOT NULL ENABLE, 
	"DATE_STT" DATE NOT NULL ENABLE, 
	"DATE_END" DATE NOT NULL ENABLE, 
	"RS_T" NUMBER(5,0), 
	"RACC_MAX" NUMBER(10,1), 
	"RACCMAX_STA" VARCHAR2(5), 
	"R_MAX" NUMBER(10,1), 
	"RMAX_STA" VARCHAR2(5), 
	"RMAX_DATE" DATE, 
	"RS_STANUM" NUMBER(5,0), 
	"RS_STACODES" VARCHAR2(4000), 
	"RS_TTL" NUMBER(10,1), 
	"RS_M" NUMBER(10,0), 
	"RS_I" NUMBER(10,1), 
	"RS_A" NUMBER(10,2), 
	"RS_Z" NUMBER(10,1), 
	"CLEVEL" VARCHAR2(10), 
	"D_IYMDHM" DATE, 
	 CONSTRAINT "PK_PROV_CLI_RHRE_PROCESS_SURFAWST" PRIMARY KEY ("CREGION", "DATE_STT", "DATE_END")
  USING INDEX  ENABLE
   ) ;
