CREATE TABLE "CLIMATE_RAIN"."SURF_AWST_CLI_PRE_HOR_RANKING" 
   (	"HOURS_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"DDATETIME" DATE NOT NULL ENABLE, 
	"STACODE" VARCHAR2(5) NOT NULL ENABLE, 
	"R" NUMBER(6,1), 
	"CPERIOD" VARCHAR2(10) NOT NULL ENABLE, 
	"RANKING_PROV" NUMBER(5,0), 
	"RANKING_CITY" NUMBER(5,0), 
	"RANKING_COUNTY" NUMBER(5,0), 
	"RANKING_TOWN" NUMBER(5,0), 
	"RANKING_STA" NUMBER(5,0), 
	"D_IYMDHM" DATE, 
	 CONSTRAINT "PK_SURFAWST_PRE_HOR_RANKING" PRIMARY KEY ("HOURS_TYPE", "DDATETIME", "STACODE", "CPERIOD")
  USING INDEX  ENABLE
   ) ;
