CREATE TABLE "CLIMATE_RAIN"."SURF_AWST_CLI_PRE_THRESHOLD" 
   (	"HOURS_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"STACODE" VARCHAR2(5) NOT NULL ENABLE, 
	"IMONTH" NUMBER(2,0) NOT NULL ENABLE, 
	"R_RANKING10" NUMBER(6,1), 
	"TIME_RANKING10" DATE, 
	"R_MIN" NUMBER(6,1), 
	"TIME_MIN" DATE, 
	"D_IYMDHM" DATE, 
	 CONSTRAINT "PK_SURFAWST_PRE_THRESHOLD" PRIMARY KEY ("HOURS_TYPE", "STACODE", "IMONTH")
  USING INDEX  ENABLE
   ) ;
