CREATE TABLE "CLIMATE_RAIN"."SURF_AWST_CLI_PRE_HOR_EXTREME" 
   (	"HOURS_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"DDATETIME" DATE NOT NULL ENABLE, 
	"STACODE" VARCHAR2(5) NOT NULL ENABLE, 
	"R" NUMBER(6,1), 
	"QC" VARCHAR2(24), 
	"QC_MANUAL" NUMBER(2,0), 
	"R_ORIGINAL" NUMBER(6,1), 
	"D_IYMDHM" DATE, 
	 CONSTRAINT "PK_SURFAWST_PRE_HOR_EXTREME" PRIMARY KEY ("HOURS_TYPE", "STACODE", "DDATETIME")
  USING INDEX  ENABLE
   ) ;
