CREATE TABLE "CLIMATE"."SURF_AWST_CLI_CA" 
   (	"STACODE" VARCHAR2(8) NOT NULL ENABLE, 
	"DDATE" DATE NOT NULL ENABLE, 
	"T" NUMBER(6,1), 
	"T_MIN" NUMBER(6,1), 
	"TV_24H" NUMBER(6,1), 
	"TV_48H" NUMBER(6,1), 
	"D_IYMDHM" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_SURF_AWST_CLI_CA" PRIMARY KEY ("STACODE", "DDATE")
  USING INDEX  ENABLE
   ) ;
