CREATE TABLE "CLIMATE"."SURF_AWST_CLI_CA_PROCESS" 
   (	"STACODE" VARCHAR2(8) NOT NULL ENABLE, 
	"ILEVEL" NUMBER(6,0), 
	"DATE_STT" DATE NOT NULL ENABLE, 
	"DATE_END" DATE NOT NULL ENABLE, 
	"IDAYS" NUMBER(6,0), 
	"TV_24H" NUMBER(6,1), 
	"TV_48H" NUMBER(6,1), 
	"TV_ACC" NUMBER(6,1), 
	"T" NUMBER(6,1), 
	"T_MIN" NUMBER(6,1), 
	"D_IYMDHM" DATE, 
	 CONSTRAINT "PK_SURF_AWST_CLI_CA_PROCESS" PRIMARY KEY ("STACODE", "DATE_STT", "DATE_END")
  USING INDEX  ENABLE
   ) ;
