CREATE TABLE "CLIMATE"."T_OTHE_STATION_CODE_TMP_TAB" 
   (	"USERID" VARCHAR2(50), 
	"STATYPE" VARCHAR2(50), 
	"STACODE" VARCHAR2(50), 
	"USERIP" VARCHAR2(100), 
	 CONSTRAINT "PK_OTHE_STATION_CODE_TMP_TAB" PRIMARY KEY ("USERID", "STATYPE", "STACODE", "USERIP")
  USING INDEX  ENABLE
   ) ;
