CREATE TABLE "CROSS_META"."T_OTHE_CROSS_COMMUNICATION" 
   (	"DDATETIME" DATE NOT NULL ENABLE, 
	"CFROM" VARCHAR2(50) NOT NULL ENABLE, 
	"CTO" VARCHAR2(50) NOT NULL ENABLE, 
	"MSG_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(1500) NOT NULL ENABLE, 
	"REPLY" VARCHAR2(1500), 
	"HANDLED" VARCHAR2(1), 
	 CONSTRAINT "PK_T_OTHE_CROSS_COMMUNICATION" PRIMARY KEY ("DDATETIME", "CFROM", "CTO")
  USING INDEX  ENABLE
   ) ;
