CREATE TABLE "CROSS_META"."T_OTHE_CROSS_DATA_DOWNLOAD" 
   (	"USERID" VARCHAR2(50) NOT NULL ENABLE, 
	"DDATETIME" DATE NOT NULL ENABLE, 
	"IP_SAVE" VARCHAR2(50) NOT NULL ENABLE, 
	"STATYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"DATAGAP" VARCHAR2(50) NOT NULL ENABLE, 
	"DATATYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"SPATIAL" VARCHAR2(1000) DEFAULT '多站点', 
	"TEMPORAL" VARCHAR2(1000) NOT NULL ENABLE, 
	"DATALENGTH" VARCHAR2(50) NOT NULL ENABLE, 
	"VARIABLE" VARCHAR2(50) DEFAULT NULL, 
	 CONSTRAINT "PK_T_OTHE_CROSS_DATA_DOWNLOAD" PRIMARY KEY ("USERID", "DDATETIME")
  USING INDEX  ENABLE
   ) ;
