CREATE TABLE "CROSS_META"."T_OTHE_CROSS_UPDATE_FILE" 
   (	"VERSION" VARCHAR2(20) NOT NULL ENABLE, 
	"FILE_NAME" VARCHAR2(40) NOT NULL ENABLE, 
	"FILE_PATH" VARCHAR2(100), 
	 CONSTRAINT "PK_T_OTHE_CROSS_UPDATE_FILE" PRIMARY KEY ("VERSION", "FILE_NAME")
  USING INDEX  ENABLE
   ) ;
