CREATE TABLE "CROSS_META"."T_OTHE_ZONE_META_BASIC_TAB" 
   (	"ADMIN_ZONE" VARCHAR2(50) NOT NULL ENABLE, 
	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"ILEVEL" NUMBER(1,0), 
	"XMIN" NUMBER(5,2), 
	"XMAX" NUMBER(5,2), 
	"YMIN" NUMBER(5,2), 
	"YMAX" NUMBER(5,2), 
	"DATAZONE" VARCHAR2(50), 
	 CONSTRAINT "PK_T_OTHE_ZONE_META_BASIC_TAB" PRIMARY KEY ("ADMIN_ZONE", "ID")
  USING INDEX  ENABLE
   ) ;
