CREATE TABLE "CROSS_META"."T_OTHE_CROSS_VERSION_INFO" 
   (	"DDATETIME" DATE NOT NULL ENABLE, 
	"VERSION" VARCHAR2(20) NOT NULL ENABLE, 
	"CONTENT" VARCHAR2(4000) NOT NULL ENABLE, 
	 CONSTRAINT "PK_T_OTHE_CROSS_VERSION_INFO" PRIMARY KEY ("DDATETIME")
  USING INDEX  ENABLE
   ) ;
