CREATE TABLE "CROSS_META"."T_OTHE_CROSS_USERS_LOG" 
   (	"USERID" VARCHAR2(50) NOT NULL ENABLE, 
	"LOGTIME" DATE NOT NULL ENABLE, 
	"USERIP" VARCHAR2(20) NOT NULL ENABLE, 
	"STATUS" NUMBER(1,0), 
	 CONSTRAINT "PK_T_OTHE_CROSS_USERS_LOG" PRIMARY KEY ("USERID", "USERIP", "LOGTIME")
  USING INDEX  ENABLE
   ) ;
