CREATE TABLE "CROSS_META"."T_OTHE_CROSS_USERS_PROPERTIES" 
   (	"USERID" VARCHAR2(50) NOT NULL ENABLE, 
	"PASSWORD" VARCHAR2(50), 
	"FULLNAME" VARCHAR2(50), 
	"DEPARTMENT" VARCHAR2(50), 
	"USERLEVEL" NUMBER(11,0), 
	"USERZONE" VARCHAR2(50), 
	"DATAZONE" VARCHAR2(50), 
	"CROSS_VER" VARCHAR2(50), 
	"IP_SAVEDATA" VARCHAR2(1000), 
	"IP_WHITELIST" VARCHAR2(4000), 
	 CONSTRAINT "PK_T_OTHE_CROSS_USERS_PROPERTIES" PRIMARY KEY ("USERID")
  USING INDEX  ENABLE
   ) ;
