CREATE TABLE "CROSS_META"."T_OTHE_ZONE_RANGE_BASIC_TAB" 
   (	"ADMIN_ZONE" VARCHAR2(50) NOT NULL ENABLE, 
	"REGION" VARCHAR2(50), 
	"DATARANGE" VARCHAR2(200), 
	 CONSTRAINT "PK_T_OTHE_ZONE_RANGE_BASIC_TAB" PRIMARY KEY ("ADMIN_ZONE")
  USING INDEX  ENABLE
   ) ;
