CREATE TABLE "CROSS_META"."T_OTHE_ZONE_CODE_TAB" 
   (	"ADMIN_CODE" VARCHAR2(12) NOT NULL ENABLE, 
	"ADMIN_ZONE" VARCHAR2(100) NOT NULL ENABLE, 
	"ILEVEL" NUMBER(1,0), 
	 CONSTRAINT "PK_T_OTHE_ZONE_CODE_TAB" PRIMARY KEY ("ADMIN_CODE")
  USING INDEX  ENABLE
   ) ;
