CREATE TABLE "CROSS_META"."T_OTHE_CROSS_DATA_QUERY" 
   (	"USERID" VARCHAR2(50) NOT NULL ENABLE, 
	"DDATETIME" DATE NOT NULL ENABLE, 
	"QUERY_IP" VARCHAR2(50) NOT NULL ENABLE, 
	"QUERY_TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_T_OTHE_CROSS_DATA_QUERY" PRIMARY KEY ("USERID", "DDATETIME")
  USING INDEX  ENABLE
   ) ;
